'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Events

    Partial Public Class EditEvents

        '''<summary>
        '''pnlEventsModuleEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlEventsModuleEdit As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''valSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valSummary As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''lblTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitle As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTitle As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valRequiredTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valRequiredTitle As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''lblAllDayEvent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAllDayEvent As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAllDayEvent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAllDayEvent As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblStartDateTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStartDateTime As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''dpStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dpStartDate As Global.DotNetNuke.Web.UI.WebControls.DnnDatePicker

        '''<summary>
        '''divStartTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divStartTime As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''tpStartTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tpStartTime As Global.DotNetNuke.Web.UI.WebControls.DnnTimePicker

        '''<summary>
        '''btnCopyStartdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCopyStartdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''valRequiredStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valRequiredStartDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valValidStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valValidStartDate As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''valValidRecurStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valValidRecurStartDate As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''valValidRecurStartDate2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valValidRecurStartDate2 As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''valValidStartDate2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valValidStartDate2 As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''valRequiredStartTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valRequiredStartTime As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valValidStartTime2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valValidStartTime2 As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''valConflict control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valConflict As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''valLocationConflict control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valLocationConflict As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''lblEndDateTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEndDateTime As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''dpEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dpEndDate As Global.DotNetNuke.Web.UI.WebControls.DnnDatePicker

        '''<summary>
        '''divEndTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divEndTime As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''tpEndTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tpEndTime As Global.DotNetNuke.Web.UI.WebControls.DnnTimePicker

        '''<summary>
        '''valRequiredEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valRequiredEndDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valValidEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valValidEndDate As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''valValidEndTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valValidEndTime As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''valRequiredEndTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valRequiredEndTime As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valValidEndTime2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valValidEndTime2 As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''lblDisplayEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDisplayEndDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkDisplayEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkDisplayEndDate As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''trTimeZone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trTimeZone As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblTimeZone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTimeZone As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cboTimeZone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboTimeZone As Global.DotNetNuke.Web.UI.WebControls.DnnTimeZoneComboBox

        '''<summary>
        '''lblImportance control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblImportance As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cmbImportance control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmbImportance As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCategory As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cmbCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmbCategory As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblLocation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLocation As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cmbLocation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmbLocation As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''trCustomField1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trCustomField1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblCustomField1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCustomField1 As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtCustomField1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCustomField1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''trCustomField2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trCustomField2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblCustomField2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCustomField2 As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtCustomField2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCustomField2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''trOwner control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trOwner As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblOwner control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOwner As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cmbOwner control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmbOwner As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNotes As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ftbDesktopText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ftbDesktopText As Global.DotNetNuke.UI.UserControls.TextEditor

        '''<summary>
        '''lblSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSummary As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ftbSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ftbSummary As Global.DotNetNuke.UI.UserControls.TextEditor

        '''<summary>
        '''pnlDetailPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDetailPage As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblDetailPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDetailPage As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkDetailPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkDetailPage As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''tblDetailPageDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblDetailPageDetail As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblDetailURL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDetailURL As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''URLDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents URLDetail As Global.DotNetNuke.UI.UserControls.UrlControl

        '''<summary>
        '''pnlReminder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlReminder As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblSendReminder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSendReminder As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkReminder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkReminder As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''tblReminderDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblReminderDetail As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblTimeBefore control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTimeBefore As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtReminderTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtReminderTime As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlReminderTimeMeasurement control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlReminderTimeMeasurement As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''valReminderTime2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valReminderTime2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valReminderTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valReminderTime As Global.System.Web.UI.WebControls.RangeValidator

        '''<summary>
        '''lblEmailFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmailFrom As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtReminderFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtReminderFrom As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valEmail As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''lblNotifyEmailSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNotifyEmailSubject As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSubject As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblNotifyEmailMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNotifyEmailMessage As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtReminder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtReminder As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''pnlImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlImage As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblDisplayImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDisplayImage As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkDisplayImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkDisplayImage As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''tblImageURL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblImageURL As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblImageURL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblImageURL As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ctlURL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlURL As Global.DotNetNuke.UI.UserControls.UrlControl

        '''<summary>
        '''lblWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWidth As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtWidth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valWidth As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''lblHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHeight As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHeight As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valHeight As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''pnlRecurring control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlRecurring As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblRecEvent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRecEvent As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkReccuring control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkReccuring As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rblRepeatTypeN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblRepeatTypeN As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

        '''<summary>
        '''tblRecurringDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblRecurringDetails As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEndDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblMaxRecurrences control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMaxRecurrences As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''dpRecurEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dpRecurEndDate As Global.DotNetNuke.Web.UI.WebControls.DnnDatePicker

        '''<summary>
        '''valRequiredRecurEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valRequiredRecurEndDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valValidRecurEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valValidRecurEndDate As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''valValidRecurEndDate2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valValidRecurEndDate2 As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''lblPeriodicEvent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPeriodicEvent As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rblRepeatTypeP1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblRepeatTypeP1 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

        '''<summary>
        '''tblDetailP1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblDetailP1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblEvery control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEvery As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtP1Every control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtP1Every As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmbP1Period control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmbP1Period As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''valP1Every control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valP1Every As Global.System.Web.UI.WebControls.RangeValidator

        '''<summary>
        '''valP1Every2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valP1Every2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''lblWeeklyEvent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWeeklyEvent As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rblRepeatTypeW1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblRepeatTypeW1 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

        '''<summary>
        '''tblDetailW1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblDetailW1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblRepetitionWeek control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRepetitionWeek As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtW1Every control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtW1Every As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valW1Day control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valW1Day As Global.System.Web.UI.WebControls.RangeValidator

        '''<summary>
        '''valW1Day2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valW1Day2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''lblWeekDays control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWeekDays As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''chkW1Sun control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkW1Sun As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkW1Mon control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkW1Mon As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkW1Tue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkW1Tue As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkW1Wed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkW1Wed As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkW1Thu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkW1Thu As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkW1Fri control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkW1Fri As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkW1Sat control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkW1Sat As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkW1Sun2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkW1Sun2 As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''valW1Day3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valW1Day3 As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''lblMonthlyEvent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMonthlyEvent As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rblRepeatTypeM control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblRepeatTypeM As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

        '''<summary>
        '''tblDetailM1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblDetailM1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''rblRepeatTypeM1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblRepeatTypeM1 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

        '''<summary>
        '''lblRepeatedOn1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRepeatedOn1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cmbM1Every control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmbM1Every As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''cmbM1Period control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmbM1Period As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''rblRepeatTypeM2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblRepeatTypeM2 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

        '''<summary>
        '''lblRepeatedOn2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRepeatedOn2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cmbM2Period control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmbM2Period As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblRepetitionMonth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRepetitionMonth As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtMEvery control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMEvery As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valM2Every control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valM2Every As Global.System.Web.UI.WebControls.RangeValidator

        '''<summary>
        '''valM2Every2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valM2Every2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''lblYearlyEvent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblYearlyEvent As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rblRepeatTypeY1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblRepeatTypeY1 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

        '''<summary>
        '''tblDetailY1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblDetailY1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblRepeatOnDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRepeatOnDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''dpY1Period control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dpY1Period As Global.DotNetNuke.Web.UI.WebControls.DnnDatePicker

        '''<summary>
        '''valRequiredYearEventDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valRequiredYearEventDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valValidYearEventDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valValidYearEventDate As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''pnlEnroll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlEnroll As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblAllowErollment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAllowErollment As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkSignups control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSignups As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''tblEnrollmentDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblEnrollmentDetails As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''trAllowAnonEnroll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trAllowAnonEnroll As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plAllowAnonEnroll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAllowAnonEnroll As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAllowAnonEnroll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAllowAnonEnroll As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''trTypeOfEnrollment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trTypeOfEnrollment As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblTypeOfEnrollment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTypeOfEnrollment As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rblFree control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblFree As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

        '''<summary>
        '''lblFree control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFree As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblModerated control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblModerated As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rblPaid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblPaid As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

        '''<summary>
        '''lblPaidFee control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPaidFee As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtEnrollFee control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEnrollFee As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblTotalCurrency control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalCurrency As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''valBadFee control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valBadFee As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''trPayPalAccount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trPayPalAccount As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblPayPalAccount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPayPalAccount As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtPayPalAccount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPayPalAccount As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valPayPalAccount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valPayPalAccount As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''lblMaxEnrollment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMaxEnrollment As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtMaxEnrollment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMaxEnrollment As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblCurrentEnrolled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCurrentEnrolled As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtEnrolled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEnrolled As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valMaxEnrollment2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valMaxEnrollment2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valMaxEnrollment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valMaxEnrollment As Global.System.Web.UI.WebControls.RangeValidator

        '''<summary>
        '''lblEnrollListView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEnrollListView As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkEnrollListView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnrollListView As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblEnrollmentRole control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEnrollmentRole As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddEnrollRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddEnrollRoles As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblEnrollRoleNote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEnrollRoleNote As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''divAddUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divAddUser As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblRegUsers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRegUsers As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''grdAddUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdAddUser As Global.DotNetNuke.Modules.Events.EventUserGrid

        '''<summary>
        '''divNoEnrolees control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divNoEnrolees As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblNoEnrolee control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNoEnrolee As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtNoEnrolees control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNoEnrolees As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblMaxNoEnrolees control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMaxNoEnrolees As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''valNoEnrolees control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valNoEnrolees As Global.System.Web.UI.WebControls.RangeValidator

        '''<summary>
        '''lblEnrolledUsers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEnrolledUsers As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''grdEnrollment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdEnrollment As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''lnkSelectedEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkSelectedEmail As Global.DotNetNuke.UI.WebControls.CommandButton

        '''<summary>
        '''lnkSelectedDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkSelectedDelete As Global.DotNetNuke.UI.WebControls.CommandButton

        '''<summary>
        '''pnlEventEmailRole control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlEventEmailRole As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblEventEmailChk control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEventEmailChk As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkEventEmailChk control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEventEmailChk As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''tblEventEmailRoleDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblEventEmailRoleDetail As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblEventEmailRole control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEventEmailRole As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddEventEmailRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddEventEmailRoles As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''tblEventEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblEventEmail As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblEventEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEventEmail As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEventEmailFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEventEmailFrom As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtEventEmailFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEventEmailFrom As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RegularExpressionValidator1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegularExpressionValidator1 As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''lblEventEmailSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEventEmailSubject As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtEventEmailSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEventEmailSubject As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblEventEmailBody control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEventEmailBody As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtEventEmailBody control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEventEmailBody As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''updateButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents updateButton As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cancelButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cancelButton As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''deleteButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents deleteButton As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''copyButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents copyButton As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''pnlAudit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAudit As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblCreatedBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCreatedBy As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''CreatedBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CreatedBy As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOn As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''CreatedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CreatedDate As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
