// VBConversions Note: VB project level imports
using DotNetNuke.UI;
using DotNetNuke.Services.Exceptions;
using System.Diagnostics;
using DotNetNuke.Entities.Users;
using System.Web.UI;
using System.Drawing;
using DotNetNuke.Framework;
using Microsoft.VisualBasic;
using System.Configuration;
using System.Web.UI.WebControls;
using System.Collections;
using DotNetNuke.Common.Utilities;
//using System.Linq;
	using System.Web;
using DotNetNuke.Common;
using System.Web.UI.HtmlControls;
using DotNetNuke.Services.Localization;
using System.Data;
using System;
using DotNetNuke.Data;
using DotNetNuke;
// End of VB project level imports



//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.832
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------




	namespace DotNetNuke.Modules.Events
	{
		
		///<summary>
		///EventVCal-Klasse.
		///</summary>
		///<remarks>
		///Automatisch generierte Klasse.
		///</remarks>
		public partial class EventVCal
		{
		}
	}
	

