'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Events

    Partial Public Class EventModerate

        '''<summary>
        '''pnlEventsModuleModerate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlEventsModuleModerate As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblModerateView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblModerateView As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rbModerate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbModerate As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''pnlEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlEmail As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''chkEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEmail As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblEmailFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmailFrom As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtEmailFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailFrom As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblNotifyEmailSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNotifyEmailSubject As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtEmailSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailSubject As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblNotifyEmailMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNotifyEmailMessage As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtEmailMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailMessage As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''pnlGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlGrid As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''grdRecurEvents control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdRecurEvents As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''grdEvents control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdEvents As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''grdEnrollment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdEnrollment As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''lblMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''returnButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents returnButton As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdUpdateSelected control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdateSelected As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdSelectApproveAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSelectApproveAll As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdSelectDenyAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSelectDenyAll As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdUnmarkAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUnmarkAll As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
