'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Events

    Partial Public Class EventList

        '''<summary>
        '''toolTipManager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents toolTipManager As Global.DotNetNuke.Web.UI.WebControls.DnnToolTipManager

        '''<summary>
        '''SelectCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SelectCategory As Global.DotNetNuke.Modules.Events.SelectCategory

        '''<summary>
        '''SelectLocation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SelectLocation As Global.DotNetNuke.Modules.Events.SelectLocation

        '''<summary>
        '''EventIcons control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EventIcons As Global.DotNetNuke.Modules.Events.EventIcons

        '''<summary>
        '''gvEvents control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gvEvents As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''divNoEvents control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divNoEvents As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblNoEvents control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNoEvents As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''EventIcons2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EventIcons2 As Global.DotNetNuke.Modules.Events.EventIcons
    End Class
End Namespace
