'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Events

    Partial Public Class EventEditCategories

        '''<summary>
        '''pnlEventsModuleCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlEventsModuleCategories As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''divDeleteError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divDeleteError As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblDeleteError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDeleteError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCategoryCap control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCategoryCap As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtCategoryName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCategoryName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valRequiredName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valRequiredName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''lblColorCap control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblColorCap As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtCategoryColor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCategoryColor As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cpBackColor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cpBackColor As Global.DotNetNuke.Web.UI.WebControls.DnnColorPicker

        '''<summary>
        '''ValColor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ValColor As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''lblFontColorCap control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFontColorCap As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtCategoryFontColor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCategoryFontColor As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cpForeColor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cpForeColor As Global.DotNetNuke.Web.UI.WebControls.DnnColorPicker

        '''<summary>
        '''CalFontColor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CalFontColor As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''lblPreview control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPreview As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''previewpane control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents previewpane As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblPreviewCat control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPreviewCat As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''cmdAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAdd As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''returnButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents returnButton As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''GrdCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GrdCategories As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''lblEditMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEditMessage As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
