'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Events

    Partial Public Class EventWeek

        '''<summary>
        '''toolTipManager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents toolTipManager As Global.DotNetNuke.Web.UI.WebControls.DnnToolTipManager

        '''<summary>
        '''pnlDateControls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDateControls As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lnkToday control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkToday As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''dpGoToDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dpGoToDate As Global.DotNetNuke.Web.UI.WebControls.DnnDatePicker

        '''<summary>
        '''SelectCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SelectCategory As Global.DotNetNuke.Modules.Events.SelectCategory

        '''<summary>
        '''SelectLocation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SelectLocation As Global.DotNetNuke.Modules.Events.SelectLocation

        '''<summary>
        '''EventIcons control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EventIcons As Global.DotNetNuke.Modules.Events.EventIcons

        '''<summary>
        '''lnkPrev control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkPrev As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblWeekOf control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWeekOf As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lnkNext control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkNext As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''schWeek control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents schWeek As Global.DotNetNuke.Modules.Events.ScheduleControl.ScheduleCalendar

        '''<summary>
        '''EventIcons2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EventIcons2 As Global.DotNetNuke.Modules.Events.EventIcons
    End Class
End Namespace
