'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:2.0.50727.832
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace DotNetNuke.Modules.Events

    '''<summary>
    '''EventVCal-Klasse.
    '''</summary>
    '''<remarks>
    '''Automatisch generierte Klasse.
    '''</remarks>
    Partial Public Class EventVCal
    End Class
End Namespace
