'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Events

    Partial Public Class EventDetails

        '''<summary>
        '''pnlEventsModuleDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlEventsModuleDetails As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''divMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divMessage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''divEventDetails1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divEventDetails1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''divReminder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divReminder As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''rem1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rem1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''imgNotify control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgNotify As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''cmdNotify control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdNotify As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''chkReminderRec control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkReminderRec As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rem2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rem2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''txtUserEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUserEmail As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valEmail As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''valEmail2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valEmail2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''txtReminderTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtReminderTime As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlReminderTimeMeasurement control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlReminderTimeMeasurement As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblTimeBefore control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTimeBefore As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''valReminderTime2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valReminderTime2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valReminderTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valReminderTime As Global.System.Web.UI.WebControls.RangeValidator

        '''<summary>
        '''rem3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rem3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''imgConfirmation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgConfirmation As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lblConfirmation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblConfirmation As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''divIcalendar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divIcalendar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''imgEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgEmail As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''cmdEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdEmail As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''iCal1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents iCal1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''txtUserEmailiCal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUserEmailiCal As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valEmailiCal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valEmailiCal As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''valEmailiCal2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valEmailiCal2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''divEventDetails2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divEventDetails2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''divEnrollment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divEnrollment As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''enroll1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents enroll1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''imgEnroll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgEnroll As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''cmdSignup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSignup As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''enroll4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents enroll4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''imgEnrollTooLate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgEnrollTooLate As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lblEnrollTooLate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEnrollTooLate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''enroll3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents enroll3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblNoEnrolee control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNoEnrolee As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtNoEnrolees control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNoEnrolees As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblMaxNoEnrolees control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMaxNoEnrolees As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''valNoEnrolees control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valNoEnrolees As Global.System.Web.UI.WebControls.RangeValidator

        '''<summary>
        '''valNoEnrolees2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valNoEnrolees2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''enroll5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents enroll5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblAnonEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAnonEmail As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtAnonEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAnonEmail As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valAnonEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valAnonEmail As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''valAnonEmail2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valAnonEmail2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''lblAnonName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAnonName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtAnonName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAnonName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valAnonName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valAnonName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''lblAnonTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAnonTelephone As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtAnonTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAnonTelephone As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''enroll2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents enroll2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''imgSignup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgSignup As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lblSignup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSignup As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''divEventDetails3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divEventDetails3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''divEnrollList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divEnrollList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblEnrolledUsers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEnrolledUsers As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''grdEnrollment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdEnrollment As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''cmdvEventSignups control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdvEventSignups As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''divEventDetails4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divEventDetails4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''returnButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents returnButton As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''editButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents editButton As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''editSeriesButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents editSeriesButton As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''deleteButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents deleteButton As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''deleteSeriesButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents deleteSeriesButton As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdPrint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdPrint As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''cmdvEventSeries control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdvEventSeries As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdvEvent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdvEvent As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
