'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Events

    Partial Public Class Settings

        '''<summary>
        '''lblSettingsMoved control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSettingsMoved As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''divUpgrade control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divUpgrade As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plUpgrade control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plUpgrade As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cmdUpgrade control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpgrade As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''divRetry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divRetry As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plRetry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRetry As Global.DotNetNuke.UI.UserControls.LabelControl
    End Class
End Namespace
