'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Events

    Partial Public Class EventUserGrid

        '''<summary>
        '''dropdownFilterItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dropdownFilterItem As Global.System.Web.UI.HtmlControls.HtmlSelect

        '''<summary>
        '''lblStartswith control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStartswith As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtFilterUsers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFilterUsers As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdRefreshList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdRefreshList As Global.DotNetNuke.UI.WebControls.CommandButton

        '''<summary>
        '''gvUsersToEnroll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gvUsersToEnroll As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''cmdSelectedAddUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSelectedAddUser As Global.DotNetNuke.UI.WebControls.CommandButton
    End Class
End Namespace
