// VBConversions Note: VB project level imports
using DotNetNuke.UI;
using DotNetNuke.Services.Exceptions;
using System.Diagnostics;
using DotNetNuke.Entities.Users;
using System.Web.UI;
using System.Drawing;
using DotNetNuke.Framework;
using Microsoft.VisualBasic;
using System.Configuration;
using System.Web.UI.WebControls;
using System.Collections;
using DotNetNuke.Common.Utilities;
//using System.Linq;
	using System.Web;
using DotNetNuke.Common;
using System.Web.UI.HtmlControls;
using DotNetNuke.Services.Localization;
using System.Data;
using System;
using DotNetNuke.Data;
using DotNetNuke;
// End of VB project level imports



//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


	namespace DotNetNuke.Modules.Events
	{
		
		public partial class EventUserGrid
		{
			
			///<summary>
			///dropdownFilterItem control.
			///</summary>
			///<remarks>
			///Auto-generated field.
			///To modify move field declaration from designer file to code-behind file.
			///</remarks>
			protected global::System.Web.UI.HtmlControls.HtmlSelect dropdownFilterItem;
			
			///<summary>
			///lblStartswith control.
			///</summary>
			///<remarks>
			///Auto-generated field.
			///To modify move field declaration from designer file to code-behind file.
			///</remarks>
			protected global::System.Web.UI.WebControls.Label lblStartswith;
			
			///<summary>
			///txtFilterUsers control.
			///</summary>
			///<remarks>
			///Auto-generated field.
			///To modify move field declaration from designer file to code-behind file.
			///</remarks>
			protected global::System.Web.UI.WebControls.TextBox txtFilterUsers;
			
			///<summary>
			///cmdRefreshList control.
			///</summary>
			///<remarks>
			///Auto-generated field.
			///To modify move field declaration from designer file to code-behind file.
			///</remarks>
			protected global::DotNetNuke.UI.WebControls.CommandButton cmdRefreshList;
			
			///<summary>
			///gvUsersToEnroll control.
			///</summary>
			///<remarks>
			///Auto-generated field.
			///To modify move field declaration from designer file to code-behind file.
			///</remarks>
			protected global::System.Web.UI.WebControls.GridView gvUsersToEnroll;
			
			///<summary>
			///cmdSelectedAddUser control.
			///</summary>
			///<remarks>
			///Auto-generated field.
			///To modify move field declaration from designer file to code-behind file.
			///</remarks>
			protected global::DotNetNuke.UI.WebControls.CommandButton cmdSelectedAddUser;
		}
	}
	

