// VBConversions Note: VB project level imports
using DotNetNuke.UI;
using DotNetNuke.Services.Exceptions;
using System.Diagnostics;
using DotNetNuke.Entities.Users;
using System.Web.UI;
using System.Drawing;
using DotNetNuke.Framework;
using Microsoft.VisualBasic;
using System.Configuration;
using System.Web.UI.WebControls;
using System.Collections;
using DotNetNuke.Common.Utilities;
//using System.Linq;
	using System.Web;
using DotNetNuke.Common;
using System.Web.UI.HtmlControls;
using DotNetNuke.Services.Localization;
using System.Data;
using System;
using DotNetNuke.Data;
using DotNetNuke;
// End of VB project level imports



//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



	namespace DotNetNuke.Modules.Events
	{
		
		public partial class SelectLocation
		{
			
			///<summary>
			///lblLocation control.
			///</summary>
			///<remarks>
			///Auto-generated field.
			///To modify move field declaration from designer file to code-behind file.
			///</remarks>
			protected global::System.Web.UI.WebControls.Label lblLocation;
			
			///<summary>
			///ddlLocations control.
			///</summary>
			///<remarks>
			///Auto-generated field.
			///To modify move field declaration from designer file to code-behind file.
			///</remarks>
			protected global::DotNetNuke.Web.UI.WebControls.DnnComboBox ddlLocations;
			
			///<summary>
			///btnUpdate control.
			///</summary>
			///<remarks>
			///Auto-generated field.
			///To modify move field declaration from designer file to code-behind file.
			///</remarks>
			protected global::System.Web.UI.WebControls.Button btnUpdate;
		}
	}
	

